In [1]:
# Predict where people fall on the map based on their food preferences
import pickle

with open("./pca_models/people_2d_model.pkl", "rb") as fin:
    pca_2d = pickle.load(fin)

In [2]:
# Predict with new data
import numpy as np

def transform(prefs):
    mean = np.nanmean(prefs)
    for i in range(len(prefs)):
        if np.isnan(prefs[i]):
            prefs[i] = mean

    std = np.std(prefs)
    prefs = (prefs - mean) / std
    
    prefs = prefs.reshape(1, -1)

    return pca_2d.transform(prefs)


def get_point(spreadsheet_row):
    prefs = []
    parts = spreadsheet_row.split("\t")[3:-2][:50]

    for part in parts:
        prefs.append(np.nan if part == "" else float(part))

    prefs = np.array(prefs)
    return transform(prefs)

In [3]:
while True:
    col = input("\nRow: ")
    try:
        print(get_point(col))
    except:
        print("Error :(")

[[ 4.37142025 -2.23402267]]
[[ 4.37142025 -2.23402267]]
[[ 4.37142025 -2.23402267]]
[[ 4.37142025 -2.23402267]]


C:\Users\willi\AppData\Local\Temp\ipykernel_19600\650484049.py:5: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(prefs)
c:\Users\willi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
c:\Users\willi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:223: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
c:\Users\willi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Error :(


C:\Users\willi\AppData\Local\Temp\ipykernel_19600\650484049.py:5: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(prefs)
c:\Users\willi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
c:\Users\willi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:223: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
c:\Users\willi\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\_methods.py:257: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Error :(
